macro(thrift_get_version _config_ac_PATH vmajor vminor vpatch verstr)
    file(STRINGS "${_config_ac_PATH}/configure.ac" _thrift_VER_STRING_AUX REGEX "^AC_INIT")
    #    message("_trift_VER_STRING_AUX = ${_thrift_VER_STRING_AUX}")
    string(REGEX MATCH "[0-9]+[.][0-9]+[.][0-9]+" _thrift_VER_STR ${_thrift_VER_STRING_AUX})
    string(REGEX MATCH "-dev" _thrift_DEV_PROP ${_thrift_VER_STRING_AUX})
    #    message("_thrift_VER_STR = ${_thrift_VER_STR}")
    string(REGEX MATCHALL "[0-9]+" _thrift_VER_LIST ${_thrift_VER_STR})
    #    message("_thrift_VER_LIST = ${_thrift_VER_LIST}")
    list(GET _thrift_VER_LIST 0 ${vmajor})
    list(GET _thrift_VER_LIST 1 ${vminor})
    list(GET _thrift_VER_LIST 2 ${vpatch})
    set(${verstr} "${_thrift_VER_STR}${_thrift_DEV_PROP}")
endmacro()
